# 0. import packages and read in data

In [24]:
import detectlanguage

detectlanguage.configuration.api_key = "8bfa4f869a49a2ee0ded3ac480da933d"

In [1]:
import pandas as pd
import re
from bs4 import BeautifulSoup
import unicodedata
import contractions

In [2]:
resume_df = pd.read_csv('extracted_cvs.csv', on_bad_lines='warn')
jobs_df = pd.read_csv('job_listings3.csv') #de url links werken, maar je moet ze volledig kopieren

/var/folders/8x/qw4pmxy96y33j71r3sj_v4_00000gn/T/ipykernel_4353/961090222.py:1: ParserWarning: Skipping line 8: expected 2 fields, saw 3

  resume_df = pd.read_csv('extracted_cvs.csv', on_bad_lines='warn')

In [3]:
resume_df

               file_path                                            content
0        ./CV Mikail.pdf  CURRICULUM VITAE\n\nMIKAIL MALCIKAN\n\nL I N K...
1  Ayush_Shrestha_CV.pdf  AYUSH SHRESTHA\n\nS t u d e n t\n\nABOUT ME\n\...
2  Cv_George_Lemmens.pdf  George Lemmens\n\nErvaring\n\n2020 - 2021\n\nM...
3          CV Mikail.pdf  CURRICULUM VITAE\n\nMIKAIL MALCIKAN\n\nL I N K...
4  Ayush_Shrestha_CV.pdf  AYUSH SHRESTHA\n\nS t u d e n t\n\nABOUT ME\n\...
5  Ayush_Shrestha_CV.pdf  AYUSH SHRESTHA\n\nS t u d e n t\n\nABOUT ME\n\...

In [4]:
jobs_df.head()

,Title,Address,Link,Job Description
0,Data Scientist,"Brussels, Brussels Region, Belgium",https://be.linkedin.com/jobs/view/data-scienti...,Are you looking to make a measurable impact fo...
1,Junior Data Scientist,"Ixelles, Belgium",https://be.linkedin.com/jobs/view/junior-data-...,Direct message the job poster from Pauwels Con...
2,Data Analyst,"Brussels, Brussels Region, Belgium",https://be.linkedin.com/jobs/view/data-analyst...,Direct message the job poster from Nemeon Mark...
3,"(Junior) Data, Insights & Analytics Consultant","Kortrijk, Flemish Region, Belgium",https://be.linkedin.com/jobs/view/junior-data-...,Do you want to become an expert in Data Analyt...
4,Data Scientist,"Brussels, Brussels Region, Belgium",https://be.linkedin.com/jobs/view/data-scienti...,Direct message the job poster from EUROPEAN DY...

In [5]:
jobs_df.isna().mean()

Title              0.0
Address            0.0
Link               0.0
Job Description    0.0
dtype: float64

In [6]:
jobs_df.dropna(inplace=True)

# 1.text cleaning

In [7]:
def cleaning(text):
    if not isinstance(text, str):
        return ""
    
    # Normalize Unicode characters
    text = unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode('ascii')
    
    # Expand contractions
    #text = contractions.fix(text)
    
    # Remove HTML tags
    text = BeautifulSoup(text, "html.parser").get_text()
    
    # Remove @mentions
    text = re.sub(r"@\w+", "", text)
    
    # Remove URLs
    text = re.sub(r"https?://\S+", "", text)
    
    # Remove hashtags
    text = re.sub(r"#\w+", "", text)
    
    # Remove non-ASCII characters
    text = re.sub(r"[^\x00-\x7F]+", "", text)
    
    # Remove newline characters
    text = re.sub(r"\n", " ", text)
    
    # Remove leading/trailing spaces
    text = re.sub(r"^\s+", "", text)
    text = re.sub(r"\s+$", "", text)
    
    # Remove multiple spaces
    text = re.sub(r"[ |\t]+", " ", text)
    
    # Remove parentheses and slashes
    text = re.sub(r"[()]", "", text)
    text = re.sub(r"/", " ", text)
    
    # Remove commas and periods
    text = re.sub(r",", " ", text)
    text = re.sub(r"\. ", " ", text)
    
    # Remove colons and semicolons
    text = re.sub(r":", " ", text)
    text = re.sub(r";", " ", text)
    
    # Remove numbers
    text = re.sub(r"\b\d+\b", "", text)
    
    # Remove carriage returns
    text = re.sub(r"\r", "", text)
    
    # Remove quotes and ampersands
    text = re.sub(r"\"", "", text)
    text = re.sub(r"&", "", text)
    
    # Remove hyphens, plus signs, asterisks, and equal signs
    text = re.sub(r"-", "", text)
    text = re.sub(r"\+", "", text)
    text = re.sub(r"\*", "", text)
    text = re.sub(r"\.", "", text)
    text = re.sub(r"=", "", text)
    
    # Convert to lowercase
    text = text.lower()
    
    # Remove special characters (if any left)
    text = re.sub(r"[^\w\s]", "", text)
    
    # Remove multiple spaces again just in case
    text = re.sub(r"\s+", " ", text)
    
    return text

In [8]:
# Clean and translate the 'content' column
resume_df['clean_content'] = resume_df['content'].apply(lambda x: cleaning(x))

# Clean and translate the 'Job Description' column
jobs_df['clean_description'] = jobs_df['Job Description'].apply(lambda x: cleaning(str(x)))
jobs_df['clean_address'] = jobs_df['Address'].apply(lambda x: cleaning(str(x)))

In [9]:
# Temporarily change the display options
#check cleaning function
'''with pd.option_context('display.max_colwidth', None):
    print('cleaned:',resume_df[['clean_content']])
    print('content:',resume_df[['content']])'''

'''with pd.option_context('display.max_colwidth', None):
    print('cleaned:',jobs_df['clean_description'].head())
    print('content:',jobs_df['Job Description'].head())'''

with pd.option_context('display.max_colwidth', None):
    print('cleaned:',jobs_df['clean_address'].head())
    print('content:',jobs_df['Address'].head())

cleaned: 0    brussels brussels region belgium
1                     ixelles belgium
2    brussels brussels region belgium
3     kortrijk flemish region belgium
4    brussels brussels region belgium
Name: clean_address, dtype: object
content: 0    Brussels, Brussels Region, Belgium
1                      Ixelles, Belgium
2    Brussels, Brussels Region, Belgium
3     Kortrijk, Flemish Region, Belgium
4    Brussels, Brussels Region, Belgium
Name: Address, dtype: object

In [39]:
'''# Function to detect language and handle empty text
def detect_language(text):
    if text:
        result = detectlanguage.detect(text)
        if result and isinstance(result, list) and isinstance(result[0], dict):
            return result[0]['language']
        else:
            return 'Unknown'
    else:
        return 'Empty'

# Apply the language detection function
jobs_df['clean_description_language'] = jobs_df['clean_description'].apply(detect_language)
resume_df['clean_content_language'] = resume_df['clean_content'].apply(detect_language)
'''

"# Function to detect language and handle empty text\ndef detect_language(text):\n    if text:\n        result = detectlanguage.detect(text)\n        if result and isinstance(result, list) and isinstance(result[0], dict):\n            return result[0]['language']\n        else:\n            return 'Unknown'\n    else:\n        return 'Empty'\n\n# Apply the language detection function\njobs_df['clean_description_language'] = jobs_df['clean_description'].apply(detect_language)\nresume_df['clean_content_language'] = resume_df['clean_content'].apply(detect_language)\n"

In [21]:
###
from deep_translator import GoogleTranslator

# Define a function to translate text
def translate_text(text):
    if text is None or text == '':
        return ''
    else:
        try:
            translation = GoogleTranslator(source='auto', target='en').translate(text)
            return translation
        except Exception as e:
            print(f'Error translating text: {e}')
            return

# Apply the function to the clean_description column
jobs_df['translated_description'] = jobs_df['clean_description'].apply(lambda x: translate_text(x) if x else 'Empty')

# Apply the function to the clean_address column #niet nodig
#jobs_df['translated_address'] = jobs_df['clean_address'].apply(lambda x: translate_text(x) if x else 'Empty')

# Apply the function to the clean_content column
resume_df['translated_content'] = resume_df['clean_content'].apply(lambda x: translate_text(x) if x else 'Empty')

Error translating text: are you looking to make a measurable impact for your clients with data science ready to expand your skillset in different tools methodologies and across various industries do you have an innate passion for business and entrepreneurial sense while having an interest in the technical aspects of the job what is your mission help innovative companies thrive in turning their objectives into results through smarter use of data more concretely what will you do daytoday as a data scientist you will play a vital role in the endtoend delivery of our projects therefore you will work closely with stakeholders to prioritize business requirements manage data collection analyze results provide reports model data interpret trends and patterns communicate the results and next steps effectively with clients our assignments include data audit data preparation descriptive analysis modeling presenting the results senior data scientists supervise and coach junior data scientists in delivering their projects and on internal tasks this guidance is to help junior data scientists acquire the business and technical skills to manage their projects quickly requirements do you recognize yourself your background you have a masters in management economics engineering mathematics physics biology or similar there is no standard study background for data you are fluent in english and either in dutch or french your professional skills you have good knowledge and demonstrable experience with etl and statistical packages sas spss r python spark knowledge of programming languages such as javascript spark s c is a plus you have technical expertise in data preparation data models data mining and segmentation your personal skills you have strong analytical skills to collect organize analyze and interpret large amounts of data to underline the relevant information regarding a specific business objective you have a problemsolving mindset you take a pragmatic approach regarding data science and seek out the simple solution must have you are eligible to work in belgium and the european union please be aware that we do not offer relocation support you will be a great fit if you want to be among the first employees to help us shape our organization and grow in the future you have a natural care about work quality showing a professional attitude and passion for service you are proactive autonomous and like to take initiative you can confidently interact and communicate at all levels from the frontline staff to the executive team with data experts and nonexperts alike you are curious about new techniques and tools and strive always to keep learning some signs this may not be the right fit if you dont like to interact with customers or do presentations from time to time all our data scientists are clientfacing if you are not comfortable working at the clients premises on average days a week and from our offices in brussels on average days a week if you dont have an entrepreneurial mindset and arent ready to go the extra mile to deliver quality work or contribute to an organizations growth benefits working at agilytic we aim at creating a work environment that allows you to do exceptional work grow your skillset and most importantly be happy while doing it you may work on assignments anywhere in belgium and neighboring countries like luxembourg france the netherlands and the uk you can expect to interact with it data specialists and business executives marketing process customer care we believe that data is a means to an end and not an end in itself we dont use cuttingedge techniques when not suited to the problem we need to solve we adapt to what the client truly needs even if it might look less appealing from a technical perspective for instance we wont train a neural network predicting marketing performance based on variables if a simple dashboard showing marketing efficiency across a few dimensions answers the customers question all our missions are about data and so far approximately of them havent required any machine learning salary and benefits competitive remuneration package we offer a competitive remuneration package a cafeteria plan in which you can allocate your variable remuneration to your preferred advantages extra days off electronics and cash of course training roadmap we will draft together a training roadmap taking into consideration our internal competencies as well as your interests supportive structure and transparency what we dont have in scale yet well make it up with flexibility support and transparency we will be there for you every step of the way with individual coaching and career roadmapping modern tools tools are a means to an end we want them to help you do your best work not become a bottleneck thats why you can expect uptodate hardware and software tools so that you hopefully never have to swear at your computer oh and a little bit of fun too we take our work very seriously but were not afraid to laugh at ourselves life is too short show less seniority level associate employment type fulltime job function consulting industries nonprofit organizations and primary and secondary education referrals increase your chances of interviewing at agilytic by 2x see who you know --> Text length need to be between 0 and 5000 characters
Error translating text: primary location belgiumbrussels nato body nato international staff nato is schedule fulltime application deadline may pm grade nato grade g10 summary the international board of auditors for nato iban is an independent audit body composed of six members appointed by the north atlantic council council from among candidates nominated by the member countries board members are responsible for their work only to the council the board carries out external audits of nato bodies assimilated entities and of the nato security investment programme nsip ibans mandate is to assure the council and the governments of nato member countries that funds were used according to authorization and that the financial statements are accurate and give a fair view of natos financial situation iban also evaluates natos activities with regard to their economy efficiency and effectiveness in order to achieve this mandate iban performs types of audits financial audit an examination of the financial statements of nato entities to check whether they are true and fair and their funds were properly used in accordance with the regulations in force performance audit an evaluation of the economy efficiency and effectiveness of natos activities operations and programmes nsip audit an examination of expenditures for these projects which relate to for example infrastructure equipment or information and communication systems iban conducts approximately financial statement audits per year of nato commands agencies benefit plans and other assimilated entities iban also performs between and audits annually of nsip expenditures in addition iban implements three or more performance audits each year the audit teams travel to nato and nonnato nations to carry out their work the ibans work is guided by the three core values of independence integrity and professionalism independence iban is solely responsible to the council for its work it neither seeks nor receives instructions from any other authority integrity iban conducts its work in a fair objective balanced unbiased and nonpolitical manner professionalism ibans work is planned executed and reported in accordance with international auditing principles and standards under the supervision of the principal assistant and the head administrative support section administrative officer the incumbent assists and supports the board ibans middle management and audit teams in their audit work of financial statements nsip audits and performance audits they are accountable for efficiently handling a wide range of support duties of an administrative and organisational nature for iban as well as other work as assigned the incumbent also acts as the principal assistant in their absence we offer a work experience in an interesting and challenging international environment where you will have to cooperate closely with colleagues from many different nations qualifications and experience essential the incumbent must have a general education at least to higher secondary level have a minimum of years experience in an administrative support role have strong competencies in the use of communications information software cis and information technology it platforms have experience in editing formatting and drafting official documents demonstrate the ability to manage and prioritise multiple tasks simultaneously demonstrate a strong drive for teamwork flexibility and resilience to changing requirements have strong communication skills both oral and written possess the following minimum levels of natos official languages english french v advanced in one and iii intermediate in the other d esirable the following would be considered an advantage knowledge of document management retrieval systems and database software such as ms access an advanced level of english level v both oral and written experience in using enterprise resource planning erp software experience in maintaining and updating collaborative tools prior experience within an audit or financial team and a higher level of education main accountabilities planning and execution assist with the daytoday administration related to financial and performance audits as well as nsip audits when necessary keep track of the status of financial and performance audits from the planning stage to final approval by council in the internal iban database and ensure it is uptodate perform necessary followup with the audit teams and ensure proper correspondence with nato entities organise own workload to ensure the accurate and timely execution of duties organisational efficiencies provide constructive suggestions to improve office procedures find ways to be faster better and more effective in managing information and using office tools contribute to the identification of opportunities for organisational efficiencies within ones own field of expertise information management under the supervision of the principal assistant prepare and distribute documents for meetings of the board ensure updating of the iban access databases and maintain an effective followup and or reminder system for pending actions regarding iban audits as well as a general correspondence log for iban audits type and format all kinds of documents including tables of figures requiring careful presentation using the standard software packages used by nato word excel powerpoint ensure formatting of audit reports and documents prepared by iban are in accordance with iban and nato standards oversee the paper flow into and out of the office including retrieving and organising correspondence documents including classified information work with the audit software used by iban to assist auditors in the conduct of the audits expertise development research data on information related to iban audits as directed proactively develop skills in areas such as planning organisation technology languages and effective communication liaise with other iban administrative staff to leverage knowledge knowledge management create and update the files needed for iban audits such as the collection logging and filing of documents hard copy or electronic in iban and nato automated systems maintain wellstructured paper and electronic filing systems stakeholder management liaise with points of contact to ensure efficiency in daily management of workload and processes especially for board members middle management and audit staff when at the office in brussels or abroad on mission be the point of contact for questions concerning financial and performance audits maintain all lists of internal and external contacts project management maintain and update the iban internal collaborative sites monitor and track audit recommendations in the audit software used by iban maintain and improve the internal audit databases to meet the requirements and needs of iban perform any other tasks as assigned interrelationships the incumbent reports to the iban head administrative support section administrative officer through the principal assistant the incumbent carries out administrative and support work for the board members the principal auditor the senior auditors and the auditors and serve as an occasional point of contact for staff from the entities audited by iban direct reports n a indirect reports n a competencies the incumbent must demonstrate clarity and accuracy checks own work customer service orientation takes personal responsibility for correcting problems empathy listens actively flexibility acts with flexibility initiative is decisive in a timesensitive situation organisational awareness understands organisational climate and culture teamwork expresses positive attitudes and expectations of team or team members contract contract to be offered to the successful applicant if nonseconded definite duration contract of three years duration possibility of an indefinite duration contract thereafter contract clause applicable in accordance with the nato civilian personnel regulations the successful candidate will receive a definite duration contract of three years which may be followed by an indefinite duration contract if the successful applicant is seconded from the national administration of one of natos member states a year definite duration contract will be offered which may be renewed for a further period of up to years subject to the agreement of the national authority concerned the maximum period of service in the post as a seconded staff member is six years serving staff will be offered a contract in accordance with the nato civilian personnel regulations useful information regarding application and recruitment process please note that we can only accept applications from nationals of nato member countries applications must be submitted using erecruitment system as applicable for nato civilian staff members only please apply via the internal recruitment portal link for all other applications wwwnatoint recruitment before you apply to any position we encourage you to click here and watch our video providing tips to prepare you for your application and recruitment process do you have questions on the application process in the system and not sure how to proceed click here for a video containing the information you need to successfully submit your application on time more information about the recruitment process and conditions of employment can be found at our website appointment will be subject to receipt of a security clearance provided by the national authorities of the selected candidate approval of the candidates medical file by the nato medical adviser verification of your studyies and work experience and the successful completion of the accreditation and notification process by the relevant authorities nato will not accept any phase of the recruitment and selection prepared in whole or in part by means of generative artificialintelligence ai tools including and without limitation to chatbots such as chat generative pretrained transformer chat gpt or other language generating tools nato reserves the right to screen applications to identify the use of such tools all applications prepared in whole or in part by means of such generative or creative ai applications may be rejected without further consideration at natos sole discretion and nato reserves the right to take further steps in such cases as appropriate additional information nato is committed to diversity and inclusion and strives to provide equal access to employment advancement and retention independent of gender age nationality ethnic origin religion or belief cultural background sexual orientation and disability nato welcomes applications of nationals from all member nations and strongly encourages women to apply building integrity is a key element of natos core tasks as an employer nato values commitment to the principles of integrity transparency and accountability in accordance with international norms and practices established for the defence and related security sector selected candidates are expected to be role models of integrity and to promote good governance through ongoing efforts in their work due to the broad interest in nato and the large number of potential candidates telephone or email enquiries cannot be dealt with applicants who are not successful in this competition may be offered an appointment to another post of a similar nature albeit at the same or a lower grade provided they meet the necessary requirements the nature of this position may require the staff member at times to be called upon to travel for work and or to work outside normal office hours the organization offers several worklife policies including teleworking and flexible working arrangements flexitime subject to business requirements please note that the international staff at nato headquarters in brussels belgium is a nonsmoking environment for information about the nato single salary scale grading allowances etc please visit our website detailed data is available under the salary and benefits tab show less seniority level entry level employment type fulltime job function administrative industries defense and space manufacturing referrals increase your chances of interviewing at nato by 2x see who you know --> Text length need to be between 0 and 5000 characters
Error translating text: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

KeyboardInterrupt:

In [40]:
# Temporarily change the display options
#check translation function
'''with pd.option_context('display.max_colwidth', None):
    print('cleaned:',resume_df[['clean_content']])
    print('translated:',resume_df[['translated_content']])'''

with pd.option_context('display.max_colwidth', None):
    print('cleaned:',jobs_df['clean_description'].head())
    print('translated:',jobs_df['translated_description'].head())

'''with pd.option_context('display.max_colwidth', None):
    print('cleaned:',jobs_df['clean_address'].head())
    print('translated:',jobs_df['translated_address'].head())'''

cleaned: 0    are you looking to make a measurable impact for your clients with data science ready to expand your skillset in different tools methodologies and across various industries do you have an innate passion for business and entrepreneurial sense while having an interest in the technical aspects of the job what is your mission help innovative companies thrive in turning their objectives into results through smarter use of data more concretely what will you do daytoday as a data scientist you will play a vital role in the endtoend delivery of our projects therefore you will work closely with stakeholders to prioritize business requirements manage data collection analyze results provide reports model data interpret trends and patterns communicate the results and next steps effectively with clients our assignments include data audit data preparation descriptive analysis modeling presenting the results senior data scientists supervise and coach junior data scientists in delivering their projects and on internal tasks this guidance is to help junior data scientists acquire the business and technical skills to manage their projects quickly requirements do you recognize yourself your background you have a masters in management economics engineering mathematics physics biology or similar there is no standard study background for data you are fluent in english and either in dutch or french your professional skills you have good knowledge and demonstrable experience with etl and statistical packages sas spss r python spark knowledge of programming languages such as javascript spark s c is a plus you have technical expertise in data preparation data models data mining and segmentation your personal skills you have strong analytical skills to collect organize analyze and interpret large amounts of data to underline the relevant information regarding a specific business objective you have a problemsolving mindset you take a pragmatic approach regarding data science and seek out the simple solution must have you are eligible to work in belgium and the european union please be aware that we do not offer relocation support you will be a great fit if you want to be among the first employees to help us shape our organization and grow in the future you have a natural care about work quality showing a professional attitude and passion for service you are proactive autonomous and like to take initiative you can confidently interact and communicate at all levels from the frontline staff to the executive team with data experts and nonexperts alike you are curious about new techniques and tools and strive always to keep learning some signs this may not be the right fit if you dont like to interact with customers or do presentations from time to time all our data scientists are clientfacing if you are not comfortable working at the clients premises on average days a week and from our offices in brussels on average days a week if you dont have an entrepreneurial mindset and arent ready to go the extra mile to deliver quality work or contribute to an organizations growth benefits working at agilytic we aim at creating a work environment that allows you to do exceptional work grow your skillset and most importantly be happy while doing it you may work on assignments anywhere in belgium and neighboring countries like luxembourg france the netherlands and the uk you can expect to interact with it data specialists and business executives marketing process customer care we believe that data is a means to an end and not an end in itself we dont use cuttingedge techniques when not suited to the problem we need to solve we adapt to what the client truly needs even if it might look less appealing from a technical perspective for instance we wont train a neural network predicting marketing performance based on variables if a simple dashboard showing marketing efficiency across a few dimensions answers the customers question all our missions are about data and so far approximately of them havent required any machine learning salary and benefits competitive remuneration package we offer a competitive remuneration package a cafeteria plan in which you can allocate your variable remuneration to your preferred advantages extra days off electronics and cash of course training roadmap we will draft together a training roadmap taking into consideration our internal competencies as well as your interests supportive structure and transparency what we dont have in scale yet well make it up with flexibility support and transparency we will be there for you every step of the way with individual coaching and career roadmapping modern tools tools are a means to an end we want them to help you do your best work not become a bottleneck thats why you can expect uptodate hardware and software tools so that you hopefully never have to swear at your computer oh and a little bit of fun too we take our work very seriously but were not afraid to laugh at ourselves life is too short show less seniority level associate employment type fulltime job function consulting industries nonprofit organizations and primary and secondary education referrals increase your chances of interviewing at agilytic by 2x see who you know
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      direct message the job poster from pauwels consulting john paraan john paraan talent acquisition specialist life sciences for one of the leading pharmaceutical company in brussels we are looking for a junior data scientist as a data scientist you will play a key role in developing and implementing advanced datadriven solutions to address business challenges you will collaborate closely with crossfunctional teams to analyze large datasets derive actionable insights and build predictive models using machine learning techniques additionally you will have the opportunity to contribute to research and development projects in generative ai and prompt engineering key responsibilities conduct exploratory data analysis to identify trends patterns and anomalies in large datasets develop machine learning models for predictive analytics classification and clustering tasks collaborate with engineers and software developers to deploy machine learning models into production environments research and implement stateoftheart techniques in generative ai and prompt engineering work closely with stakeholders to understand business requirements and translate them into data science solutions communicate findings and insights to nontechnical stakeholders through clear and compelling visualizations and presentations requirements bachelors or masters degree in computer science statistics mathematics or a related field proven experience as a data scientist or similar role with a strong background in machine learning and statistical analysis proficiency in programming languages such as python r or scala experience with machine learning frameworks libraries such as tensorflow pytorch or scikitlearn familiarity with techniques in generative ai including gans vaes and autoregressive models knowledge of prompt engineering techniques for natural language processing tasks strong problemsolving skills and the ability to work independently and collaboratively in a fastpaced environment excellent communication and interpersonal skills preferred qualifications phd in computer science statistics mathematics or a related field experience working with largescale datasets and distributed computing frameworks eg spark publications or contributions to the field of generative ai or prompt engineering familiarity with cloud computing platforms such as aws google cloud or azure english only what are we looking for junior profile with knowledge in data science good knowledge in generative ai projects during internship for example fluent in english what do we offer challenging projects based on your interests and skills personal followup and clear transparent communication both before and after commencement of employment possibility to follow extra training inspiring network events and legendary after work drinks strong network of industry leading clients expertise within it engineering and life sciences a flying start for every junior growth opportunities and possibility to share gathered knowledge for more senior employees show less seniority level entry level employment type fulltime job function engineering and information technology industries staffing and recruiting pharmaceutical manufacturing and data infrastructure and analytics referrals increase your chances of interviewing at pauwels consulting by 2x see who you know
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        direct message the job poster from nemeon mark verheyden phd mark verheyden phd founder at nemeon who we are nemeon is a data and ai consulting company that aims to solve realworld problems for smbs and midmarket organizations our focus is the setup of scalable and secure data platforms that allow for reporting in power bi for example and ai applications our focus industries are logistics construction leisure job requirements what we are looking for in our experienced data analysts able to collect and organize data translate business requirements into actionable questions the data analyst gets his her high from finding patterns in data the ideal candidate combines technical skills with business thinking the attitude were looking for can do mentality customeroriented growth mindset teamplay the hard skills youll need sql data visualization knowledge power bi tableau quicksight data modeling translate business requirements into actionable questions what we offer a good salary obviously and a company car with fuel card and unlimited mileage extra benefits health insurance group insurance representation allowance a chance to shape a fastmoving company learning tracks to develop yourself further show less seniority level midsenior level employment type fulltime job function analyst and consulting industries information technology services referrals increase your chances of interviewing at nemeon by 2x see who you know

"with pd.option_context('display.max_colwidth', None):\n    print('cleaned:',jobs_df['clean_address'].head())\n    print('translated:',jobs_df['translated_address'].head())"

# 2.similarity matching

In [ ]:
#pip install spacy

#import spacy.cli
#spacy.cli.download("en_core_web_md") #(this is the medium size model 40mb)
#or
#spacy.cli.download("en_core_web_lg") (this is the large model 700mb) we should maybe switch at the end to increase model performance

In [ ]:
import spacy

In [ ]:
nlp = spacy.load("en_core_web_md")

### testing

In [ ]:
j1 = nlp(jobs_df['clean_description'][0])
j1

are you looking to make a measurable impact for your clients with data science? ready to expand your skillset in different tools  methodologies  and across various industries? do you have an innate passion for business and entrepreneurial sense while having an interest in the technical aspects of the job? what is your mission? help innovative companies thrive in turning their objectives into results  through smarter use of data more concretely  what will you do daytoday? as a data scientist  you will play a vital role in the endtoend delivery of our projects therefore  you will work closely with stakeholders to  prioritize business requirements manage data collection analyze results provide reports model data interpret trends and patterns communicate the results and next steps effectively with clients our assignments include  data audit data preparation descriptive analysis modeling presenting the results senior data scientists supervise and coach junior data scientists in delivering their projects and on internal tasks this guidance is to help junior data scientists acquire the business and technical skills to manage their projects quickly requirements do you recognize yourself? your background you have a master's in management economics  engineering  mathematics  physics  biology  or similar  there is no standard study background for data you are fluent in english and either in dutch or french your professional skills you have good knowledge and demonstrable experience with etl and statistical packages sas  spss  r  python  spark knowledge of programming languages such as javascript  spark  s  c is a plus you have technical expertise in data preparation  data models  data mining  and segmentation your personal skills you have strong analytical skills to collect  organize  analyze  and interpret large amounts of data to underline the relevant information regarding a specific business objective you have a problemsolving mindset  you take a pragmatic approach regarding data science and seek out the simple solution must have you are eligible to work in belgium and the european union please be aware that we do not offer relocation support you will be a great fit if  you want to be among the first employees to help us shape our organization and grow in the future you have a natural care about work quality  showing a professional attitude and passion for service you are proactive  autonomous  and like to take initiative you can confidently interact and communicate at all levels  from the frontline staff to the executive team  with data experts and nonexperts alike you are curious about new techniques and tools and strive always to keep learning some signs this may not be the right fit  if you don't like to interact with customers or do presentations from time to time all our data scientists are clientfacing if you are not comfortable working at the client's premises on average  days a week and from our offices in brussels on average  days a week if you don't have an entrepreneurial mindset and aren't ready to go the extra mile to deliver quality work or contribute to an organization's growth benefits working at agilytic we aim at creating a work environment that allows you to do exceptional work  grow your skillset and  most importantly  be happy while doing it you may work on assignments anywhere in belgium and neighboring countries like luxembourg  france  the netherlands  and the uk you can expect to interact with it data specialists and business executives marketing  process  customer care we believe that data is a means to an end and not an end in itself we don't use cuttingedge techniques when not suited to the problem we need to solve we adapt to what the client truly needs  even if it might look less appealing from a technical perspective for instance  we won't train a neural network predicting marketing performance based on  variables if a simple dashboard showing marketing efficiency across a few dimensions answers the customer's question all our missions are about data  and so far  approximately % of them haven't required any machine learning salary and benefits competitive remuneration package  we offer a competitive remuneration package  a cafeteria plan in which you can allocate your variable remuneration to your preferred advantages extra days off  electronics and cash of course training roadmap  we will draft together a training roadmap  taking into consideration our internal competencies as well as your interests supportive structure and transparency  what we don't have in scale yet  we'll make it up with flexibility  support  and transparency we will be there for you every step of the way  with individual coaching and career roadmapping modern tools  tools are a means to an end we want them to help you do your best work  not become a bottleneck that's why you can expect uptodate hardware and software tools so that you hopefully never have to swear at your computer oh  and a little bit of fun too  we take our work very seriously  but we're not afraid to laugh at ourselves life is too short show less seniority level associate employment type fulltime job function consulting industries nonprofit organizations and primary and secondary education referrals increase your chances of interviewing at agilytic by 2x see who you know

In [ ]:
r1 = nlp(resume_df['clean_content'][0])
r1

curriculum vitae mikail malcikan l i n k e d i n personal profile motivated business engineering master's student with strong analytical and problemsolving skills adaptable and dedicated  i excel in collaborative team environments eager to contribute academic and practical expertise to drive innovative solutions for organizational success talents and skills flexible and stressresistant it knowledge  ms office java r sql python pyspark spss sap contact gsm      email  mikailmalcikancom gaverstraat    wondelgem education universiteit gent master of science in business engineering  data analytics skills  pyspark sql data analysis python r modeling and simulation related  studentenvereniging flux bestuurslid  penningmeester winner of kaggle competition room price prediction dataset machine learning atheneum wispelberg aso  economie wiskunde experiences studentjobs claimhandler  gates event worker  sevent orderpicker  dsv solutions sorter  bpost orderpicker  barvatar delivery associate  albert heijn carwash attendant  getawash languages dutch english turkish french interests and hobbies passionate about the automotive sector  particularly focused on the electrification of vehicles enthusiastic about staying abreast of the latest developments and innovations in the industry outside of professional pursuits  i am interested in sports  with a keen interest in cycling and weightlifting

In [ ]:
r2 = nlp(resume_df['clean_content'][2])
r2

george lemmens ervaring    mowi en bakkerij notredame inpakken  logistiek en verkoop  burger king en bakkerij notredame keuken en verkoop  az zeno schoonmaak  albert heijn rekkenvuller contact telefoon  email lemmensgeorgecom adres rond den heerdstraat    brugge educatie  latijnwiskunde sintjozef humaniora heden burgerlijk ingenieur afstudeerrichting biomedische ingenieurstechnieken universiteit gent skills microsoft word microsoft powerpoint microsoft excel python maple talen nederlands  moedertaal engels  vlot frans  basis

In [ ]:
j1.similarity(r1)

0.905266056330655

In [ ]:
j1.similarity(r2)

0.3258069352590815

In [ ]:
j1_nouns = " ".join([token.lemma_ for token in j1 if token.pos_ == 'NOUN'])
r1_nouns = " ".join([token.lemma_ for token in r1 if token.pos_ == 'NOUN'])
r2_nouns = " ".join([token.lemma_ for token in r2 if token.pos_ == 'NOUN'])


j1_verbs = " ".join([token.lemma_ for token in j1 if token.pos_ == 'VERB'])
r1_verbs = " ".join([token.lemma_ for token in r1 if token.pos_ == 'VERB'])
r2_verbs = " ".join([token.lemma_ for token in r2 if token.pos_ == 'VERB'])


j1_adjs = " ".join([token.lemma_ for token in j1 if token.pos_ == 'ADJ'])
r1_adjs = " ".join([token.lemma_ for token in r1 if token.pos_ == 'ADJ'])
r2_adjs = " ".join([token.lemma_ for token in r2 if token.pos_ == 'ADJ'])

In [ ]:
print(nlp(j1_nouns).similarity(nlp(r1_nouns)))
print(nlp(j1_nouns).similarity(nlp(r2_nouns)))

0.9528472237395565
0.6108765039901467

In [ ]:
print(nlp(j1_verbs).similarity(nlp(r1_verbs)))
print(nlp(j1_verbs).similarity(nlp(r2_verbs)))

0.8680568332617608
0.5007512495849951

In [ ]:
print(nlp(j1_adjs).similarity(nlp(r1_adjs)))
print(nlp(j1_adjs).similarity(nlp(r2_adjs)))

0.9196338919736171
0.0

/var/folders/8x/qw4pmxy96y33j71r3sj_v4_00000gn/T/ipykernel_1825/955577902.py:2: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  print(nlp(j1_adjs).similarity(nlp(r2_adjs)))

### trying

In [ ]:
i = 1

In [ ]:
resume_df['clean_content'][i]

"ayush shrestha s t u d e n t about me  ayush1214shresthacom sh1214shrestha  as a future graduate from the business engineering in data science program  my passion lies in the fields of data science  machine learning  and beyond i am deeply intrigued by the power of datadriven insights to transform businesses and am eager to contribute my skills and knowledge to this dynamic field torhoutse steenweg    sintandries experiences rijbewijs b education oct    bijleshuis private tutor msc business engineering  data analytics ghent university    programming languages python r java sql languages english french dutch at bijleshuis  i served as a private tutor  providing tailored schooling to students spanning various age groups in subjects such as economics  mathematics  physics  and more it was a gratifying experience to help students achieve academic success and build confidence in their abilities across diverse subjects jun   jul  pittman seafoods administrative assistant and receptionist at pittman seafoods  i assumed the role of receptionist  taking charge of administrative duties and assisting with accounting tasks it was a dynamic role that allowed me to contribute to various aspects of the company's operations while ensuring smooth daytoday functioning oct   dec  everest analytics data consultant as a data scientist at everest analytics  i worked on the zoetjes and snoetjes project  creating a classification model to predict applicant compatibility with shelter cats it was a rewarding experience  utilizing my skills to match potential pet owners with their perfect companions relevant projects machine learning  hotel room price prediction kaggle winner in r the project involved utilizing various machine learning techniques to predict hotel room prices in r through a strategic blend of feature engineering and finetuning hyperparameters  we secured victory by optimizing predictive accuracy and performance big data  comparing social media pages in pyspark we analyzed large instagram datasets  enabling a comprehensive comparison of social media engagement across competing brands this approach facilitated the efficient processing of big data  providing valuable business insights into the relative performance of social media pages social media web analytics  using social media data to predict box office earnings in r we predicted box office earnings by harnessing social media data through web scraping from diverse online sources and employing natural language processing techniques  we achieved accurate predictions of box office earnings by analyzing social media sentiments and trends"

In [ ]:
# Tokenize the resume content (assumes one resume per DataFrame row)
resume_doc = nlp(resume_df['clean_content'][i])

# Create a new column in jobs_df to hold similarity scores
jobs_df['similarity_measure'] = 0.0  # Initialize with default value

# Calculate the similarity of the resume with each job description
for idx, row in jobs_df.iterrows():
    job_doc = nlp(row['clean_description'])
    similarity = resume_doc.similarity(job_doc)  # Calculate similarity
    jobs_df.at[idx, 'similarity_measure'] = similarity  # Assign similarity to the DataFrame

# Display the DataFrame with the added similarity measure column
jobs_df=jobs_df.sort_values('similarity_measure', ascending=False)

In [ ]:
jobs_df.head()

,Title,Address,Link,Job Description,clean_description,clean_address,translated_description,translated_address,similarity_measure
47,Research Scientist,"Leuven, Flemish Region, Belgium",https://be.linkedin.com/jobs/view/research-sci...,ArtiQ (a Clario Company) is seeking a Research...,artiq a clario company is seeking a research s...,leuven flemish region belgium,,,0.980858
25,Data Analyst,"Antwerp, Flemish Region, Belgium",https://be.linkedin.com/jobs/view/data-analyst...,Functieomschrijving The data analysts of each...,functieomschrijving the data analysts of each ...,antwerp flemish region belgium,,,0.980852
14,Data scientist,"Antwerp, Flemish Region, Belgium",https://be.linkedin.com/jobs/view/data-scienti...,Functieomschrijving The data analysts in each...,functieomschrijving the data analysts in each ...,antwerp flemish region belgium,,,0.980833
1,Junior Data Scientist,"Ixelles, Belgium",https://be.linkedin.com/jobs/view/junior-data-...,Direct message the job poster from Pauwels Con...,direct message the job poster from pauwels con...,ixelles belgium,,,0.980016
19,Data Scientist,"Brussels, Brussels Region, Belgium",https://be.linkedin.com/jobs/view/data-scienti...,Direct message the job poster from Exsolvæ Hug...,direct message the job poster from exsolv hugo...,brussels brussels region belgium,,,0.979827

In [ ]:
jobs_df.tail()

,Title,Address,Link,Job Description,clean_description,clean_address,translated_description,translated_address,similarity_measure
48,Bmatix - Junior Data Engineer,"Kontich, Flemish Region, Belgium",https://be.linkedin.com/jobs/view/bmatix-junio...,Who We Are Bmatix specialiseert zich in Busin...,who we are bmatix specialiseert zich in busine...,kontich flemish region belgium,,,0.432452
49,Elektricien,"Zwijndrecht, Flemish Region, Belgium",https://be.linkedin.com/jobs/view/elektricien-...,"Cegelec, een merk van VINCI Energies, is gespe...",cegelec een merk van vinci energies is gespe...,zwijndrecht flemish region belgium,,,0.409590
34,Data Analyst,Antwerp Metropolitan Area,https://be.linkedin.com/jobs/view/data-analyst...,Direct message the job poster from Cartière Ro...,direct message the job poster from cartire rob...,antwerp metropolitan area,,,0.280198
42,Data Analyst,"Brussels, Brussels Region, Belgium",https://be.linkedin.com/jobs/view/data-analyst...,"Pour un de nos client, acteur bancaire, nous s...",pour un de nos client acteur bancaire nous s...,brussels brussels region belgium,,,0.266670
36,Junior Data Analyst,"Flemish Brabant, Flemish Region, Belgium",https://be.linkedin.com/jobs/view/junior-data-...,Direct message the job poster from Cartière Ma...,direct message the job poster from cartire mar...,flemish brabant flemish region belgium,,,0.241206