In [2]:
import pandas as pd

In [3]:
# Load VDAB data
vdab_file_path = 'C:/Users/Cool_/Documents/GitHub/PPA/hr_tool_irakli/vdab_categories.csv'
vdab_jobs = pd.read_csv(vdab_file_path)

In [4]:
vdab_jobs.head()

,Unnamed: 0.1,Unnamed: 0,url,title,employer,location,description,description_translated,title_translated,keywords,top_categories
0,0,0,https://www.vdab.be/vindeenjob/vacatures/68793122,technisch aankoopassistent,le grand & associates,kortrijk,Functieomschrijving LGA Engineering is een rek...,Job description LGA Engineering is a recruitme...,technical purchasing assistant,"{'Profile Profile Experience', 'recruitment', ...","['Administration', 'Sales', 'Logistics, transp..."
1,1,1,https://www.vdab.be/vindeenjob/vacatures/68793123,pricing analist,lga engineering,provincie vlaams-brabant,Functieomschrijving Heb jij een passie voor de...,Job description Do you have a passion for the ...,pricing analist,"{'Job', 'career', 'job', 'competencies', 'logi...","['Sales', 'Administration', 'Creative jobs']"
2,2,2,https://www.vdab.be/vindeenjob/vacatures/68793124,pricing analist maritiem,lga engineering,antwerpen,Functieomschrijving Voor onze logistieke klant...,Job description For our logistics customer in ...,maritime pricing analyst,"{'Job', 'Offer Offer', 'contract prices', 'Ana...","['Administration', 'Sales', 'Logistics, transp..."
3,3,3,https://www.vdab.be/vindeenjob/vacatures/68793125,warehouse teamleader,start people,herentals,Functieomschrijving Onze klant gevestigd in He...,Job description Our client based in Herentals ...,warehouse team leader,"{'operating logistics', 'role', 'globally oper...","['Administration', 'Logistics, transport & pur..."
4,4,4,https://www.vdab.be/vindeenjob/vacatures/68793126,grafisch vormgever,start people,pelt,Functieomschrijving 1 op de 10 gezinnen geniet...,Job description 1 in 10 families already enjoy...,graphical designer,"{'Job', 'designing', 'wooden windows', 'doors'...","['Administration', 'Sales', 'Creative jobs']"

In [10]:
vdab_jobs['province'] = vdab_jobs['province'].replace('Brussels-Capital Region', 'Brussels')

In [15]:
vdab_jobs.loc[vdab_jobs.index == 3806, 'province'] = 'East Flanders'
vdab_jobs.loc[vdab_jobs.index == 3816, 'province'] = 'East Flanders'
vdab_jobs.loc[vdab_jobs.index == 3820, 'province'] = 'East Flanders'
vdab_jobs.loc[vdab_jobs.index == 3841, 'province'] = 'East Flanders'
vdab_jobs.loc[vdab_jobs.index == 2267, 'province'] = 'Antwerp'
vdab_jobs.loc[vdab_jobs.index == 3237, 'province'] = 'Limburg'

In [16]:
vdab_jobs["province"].value_counts()

West Flanders      3195
East Flanders      3114
Antwerp            2275
Flemish Brabant    1060
Limburg             961
Brussels            355
Hainaut              90
Walloon Brabant      48
Liège                23
Namur                 5
Luxembourg            1
Name: province, dtype: int64

In [5]:
# Set display option to show all rows
pd.set_option('display.max_rows', None)

# Display the complete output of the value_counts for the location column
location_counts = vdab_jobs["location"].value_counts()

print(location_counts)

# Revert display option to default
pd.reset_option('display.max_rows')

antwerpen                                   388
gent                                        361
roeselare                                   286
waregem                                     252
oudenaarde                                  221
harelbeke                                   203
kortrijk                                    176
brussel                                     174
mechelen                                    152
brugge                                      140
deinze                                      139
turnhout                                    125
wevelgem                                    125
wetteren                                    123
aalter                                      121
genk                                        119
aalst                                       112
wielsbeke                                   111
hasselt                                     110
puurs-sint-amands                           107
beveren-waas                                 98
herentals                                    94
sint-niklaas                                 86
vilvoorde                                    85
kruisem                                      83
lokeren                                      82
izegem                                       77
deerlijk                                     75
nazareth                                     71
ieper                                        70
willebroek                                   68
geel                                         68
ronse                                        67
zele                                         66
ooigem                                       66
oostende                                     64
tielt                                        64
temse                                        64
dendermonde                                  64
heverlee                                     63
leuven                                       62
kuurne                                       61
zaventem                                     59
evergem                                      58
tienen                                       57
doel                                         56
poperinge                                    56
zwevegem                                     54
eeklo                                        52
wortegem-petegem                             49
menen                                        48
zottegem                                     47
erembodegem                                  47
ardooie                                      47
lier                                         47
grobbendonk                                  47
zulte                                        47
oudsbergen                                   46
provincie antwerpen                          45
merelbeke                                    45
olen                                         44
pelt                                         44
lommel                                       44
ninove                                       44
tessenderlo                                  44
heusden-zolder                               44
meulebeke                                    42
berchem                                      42
heist-op-den-berg                            41
oostrozebeke                                 41
londerzeel                                   41
arendonk                                     41
wijnegem                                     40
maldegem                                     40
kontich                                      40
ternat                                       39
anzegem                                      37
deurne                                       37
wingene                                      37
drongen                                      37
desteldonk                                   36
sint-truiden                                 36
regio antwerpen                              36
sint-katelijne-waver                         36
tongeren                                     35
bornem                                       35
provincie oost-vlaanderen                    34
gavere                                       33
avelgem                                      33
knokke-heist                                 33
zwijndrecht                                  33
hooglede                                     33
sint-eloois-vijve                            32
halle                                        32
paal                                         31
mol                                          31
wilrijk                                      31
zwevezele                                    30
sint-joost-ten-node                          30
groot-bijgaarden                             29
aarschot                                     29
ingelmunster                                 29
buggenhout                                   29
lochristi                                    29
sint-gillis                                  29
asse                                         28
lummen                                       28
moeskroen                                    28
melle                                        28
gullegem                                     28
beerse                                       27
bree                                         27
kallo                                        27
ruiselede                                    27
staden                                       27
zonhoven                                     27
gits                                         26
bissegem                                     26
beringen                                     26
oostkamp                                     26
regio dendermonde - wetteren                 25
wommelgem                                    25
hoogstraten                                  25
westerlo                                     25
geraardsbergen                               25
kluisbergen                                  25
aartselaar                                   25
dilsen-stokkem                               24
diest                                        24
herent                                       24
provincie vlaams-brabant                     24
machelen                                     24
diepenbeek                                   24
diksmuide                                    24
borgerhout                                   23
beveren-leie                                 23
bavikhove                                    23
merksem                                      23
schoten                                      23
ranst                                        23
provincie west-vlaanderen                    22
oostnieuwkerke                               22
hamme                                        22
wondelgem                                    22
wervik                                       21
zeebrugge                                    21
destelbergen                                 21
kapellen                                     21
overijse                                     21
beernem                                      21
kruibeke                                     20
regio waasland                               20
blaasveld                                    20
kampenhout                                   20
rijkevorsel                                  19
halen                                        19
eke                                          18
zellik                                       18
herzele                                      18
diegem                                       17
zedelgem                                     17
meer                                         16
maasmechelen                                 16
relegem                                      16
sint-gillis-waas                             16
ledegem                                      16
desselgem                                    15
boortmeerbeek                                15
regio gent                                   15
sint-andries                                 15
erpe-mere                                    15
kortemark                                    15
gentbrugge                                   15
verrebroek                                   15
torhout                                      15
elsene                                       15
ham                                          14
veurne                                       14
wemmel                                       14
zwijnaarde                                   14
moorslede                                    14
wilsele                                      14
anderlecht                                   13
zutendaal                                    13
oostakker                                    13
nieuwpoort                                   13
rotselaar                                    13
oudenburg                                    13
brasschaat                                   13
grimbergen                                   13
adegem                                       12
brakel                                       12
dessel                                       12
landen                                       12
peruwelz                                     12
regio bornem - puurs - willebroek            12
koolskamp                                    12
balen                                        12
malle                                        12
hulste                                       11
dudzele                                      11
houthalen                                    11
oostvleteren                                 11
wavre                                        11
lievegem                                     11
etterbeek                                    11
strombeek-bever                              11
bilzen                                       11
meerhout                                     11
houthalen-helchteren                         11
moen                                         11
wolvertem                                    11
zwalm                                        11
melsele                                      11
herk-de-stad                                 10
lendelede                                    10
horebeke                                     10
blankenberge                                 10
de haan                                      10
heule                                        10
regio mechelen                               10
evere                                        10
duffel                                       10
nijlen                                       10
mortsel                                       9
sint-denijs-westrem                           9
laarne                                        9
sint-stevens-woluwe                           9
lauwe                                         9
bavegem                                       9
lubbeek                                       9
koksijde                                      9
lebbeke                                       9
hamont-achel                                  9
neder-over-heembeek                           9
jette                                         9
ekeren                                        8
brecht                                        8
provincie limburg                             8
edegem                                        8
maaseik                                       8
zelzate                                       8
niel                                          8
zonnebeke                                     8
komen                                         8
rumbeke                                       8
regio boom-aartselaar                         8
westrozebeke                                  8
tielt-winge                                   8
rumst                                         8
herenthout                                    8
oudergem                                      8
boom                                          8
sint-lievens-houtem                           8
zemst                                         8
nivelles                                      8
oud-turnhout                                  7
bekkevoort                                    7
lichtervelde                                  7
vichte                                        7
kortenberg                                    7
kasterlee                                     7
putte                                         7
kalken                                        7
bocholt                                       7
lanaken                                       7
dilbeek                                       7
stekene                                       7
essen                                         7
meetkerke                                     7
emelgem                                       7
dadizele                                      7
gistel                                        7
blandain                                      7
hoeselt                                       7
laakdal                                       7
riemst                                        7
jabbeke                                       7
regio halle                                   7
pittem                                        7
schaarbeek                                    7
lede                                          6
aarsele                                       6
afsnee                                        6
kachtem                                       6
alken                                         6
de panne                                      6
haren (brussel-stad)                          6
kessel-lo                                     6
regio beringen - tessenderlo                  6
brucargo                                      6
ganshoren                                     6
lanklaar                                      6
lissewege                                     6
pulle                                         6
bredene                                       6
mariakerke                                    6
bonheiden                                     6
meise                                         6
nieuwerkerken                                 6
oosterzele                                    6
peer                                          6
herne                                         6
braine-l'alleud                               6
zandhoven                                     6
houthulst                                     6
regio turnhout                                6
keerbergen                                    6
vorst                                         6
steenokkerzeel                                5
regio asse                                    5
merksplas                                     5
sint-jans-molenbeek                           5
affligem                                      5
sint-michiels                                 5
vilvoorde cargovil                            5
kalmthout                                     5
kuringen                                      5
dentergem                                     5
tournai                                       5
borgloon                                      5
bellegem                                      5
regio leuven                                  5
rekkem                                        5
oudegem                                       5
haacht                                        5
ruddervoorde                                  5
merchtem                                      5
drogenbos                                     5
regio herentals - westerlo                    5
regio ninove - geraardsbergen - zottegem      5
loppem                                        5
assenede                                      5
court-saint-etienne                           5
borsbeke                                      5
sint-pieters-leeuw                            5
sint-martens-latem                            5
gijzegem                                      5
stabroek                                      4
leopoldsburg                                  4
muizen                                        4
berlare                                       4
roosdaal                                      4
vlaanderen                                    4
luik                                          4
regio hasselt                                 4
louvain-la-neuve                              4
regio kontich - mortsel - ranst               4
ichtegem                                      4
welle                                         4
langemark                                     4
mollem                                        4
beselare                                      4
berlaar                                       4
boutersem                                     4
wuustwezel                                    4
hemiksem                                      4
huizingen                                     4
lessines                                      4
regio genk                                    4
hoboken                                       4
kinrooi                                       4
retie                                         4
assebroek                                     4
dworp                                         3
tisselt                                       3
hannuit                                       3
beveren-aan-den-ijzer                         3
langemark-poelkapelle                         3
hoegaarden                                    3
begijnendijk                                  3
wiekevorst                                    3
hillegem                                      3
chaudfontaine                                 3
leest                                         3
lot                                           3
ukkel                                         3
regio roeselare - izegem                      3
grace-hollogne                                3
watermaal-bosvoorde                           3
sint-agatha-berchem                           3
regio aalst                                   3
ruisbroek                                     3
haaltert                                      3
dottenijs                                     3
vorselaar                                     3
gierle                                        3
steenhuffel                                   3
vlezenbeek                                    3
zuienkerke                                    3
koekelberg                                    3
moorsel                                       3
middelkerke                                   3
komen-waasten                                 3
beveren (roeselare)                           3
lembeke                                       3
oedelem                                       3
kessel                                        3
huldenberg                                    3
regio kortrijk                                3
schilde                                       3
aalbeke                                       3
otegem                                        3
mater                                         3
egem                                          3
geluwe                                        3
damme                                         3
bottelare                                     3
lint                                          3
proven                                        3
westkerke                                     3
regio vilvoorde - zaventem                    3
maarkedal                                     3
wellen                                        3
ertvelde                                      3
regio brugge                                  3

In [6]:
location_province_mapping = {
    "antwerpen": "Antwerp",
    "gent": "East Flanders",
    "roeselare": "West Flanders",
    "waregem": "West Flanders",
    "oudenaarde": "East Flanders",
    "harelbeke": "West Flanders",
    "kortrijk": "West Flanders",
    "brussel": "Brussels-Capital Region",
    "mechelen": "Antwerp",
    "brugge": "West Flanders",
    "deinze": "East Flanders",
    "turnhout": "Antwerp",
    "wevelgem": "West Flanders",
    "wetteren": "East Flanders",
    "aalter": "East Flanders",
    "genk": "Limburg",
    "aalst": "East Flanders",
    "wielsbeke": "West Flanders",
    "hasselt": "Limburg",
    "puurs-sint-amands": "Antwerp",
    "beveren-waas": "East Flanders",
    "herentals": "Antwerp",
    "sint-niklaas": "East Flanders",
    "vilvoorde": "Flemish Brabant",
    "kruisem": "East Flanders",
    "lokeren": "East Flanders",
    "izegem": "West Flanders",
    "deerlijk": "West Flanders",
    "nazareth": "East Flanders",
    "ieper": "West Flanders",
    "willebroek": "Antwerp",
    "geel": "Antwerp",
    "ronse": "East Flanders",
    "zele": "East Flanders",
    "ooigem": "West Flanders",
    "oostende": "West Flanders",
    "tielt": "West Flanders",
    "temse": "East Flanders",
    "dendermonde": "East Flanders",
    "heverlee": "Flemish Brabant",
    "leuven": "Flemish Brabant",
    "kuurne": "West Flanders",
    "zaventem": "Flemish Brabant",
    "evergem": "East Flanders",
    "tienen": "Flemish Brabant",
    "doel": "East Flanders",
    "poperinge": "West Flanders",
    "zwevegem": "West Flanders",
    "eeklo": "East Flanders",
    "wortegem-petegem": "East Flanders",
    "menen": "West Flanders",
    "zottegem": "East Flanders",
    "erembodegem": "East Flanders",
    "ardooie": "West Flanders",
    "lier": "Antwerp",
    "grobbendonk": "Antwerp",
    "zulte": "East Flanders",
    "oudsbergen": "Limburg",
    "provincie antwerpen": "Antwerp",
    "merelbeke": "East Flanders",
    "olen": "Antwerp",
    "pelt": "Limburg",
    "lommel": "Limburg",
    "ninove": "East Flanders",
    "tessenderlo": "Limburg",
    "heusden-zolder": "Limburg",
    "meulebeke": "West Flanders",
    "berchem": "Antwerp",
    "heist-op-den-berg": "Antwerp",
    "oostrozebeke": "West Flanders",
    "londerzeel": "Flemish Brabant",
    "arendonk": "Antwerp",
    "wijnegem": "Antwerp",
    "maldegem": "East Flanders",
    "kontich": "Antwerp",
    "ternat": "Flemish Brabant",
    "anzegem": "West Flanders",
    "deurne": "Antwerp",
    "wingene": "West Flanders",
    "drongen": "East Flanders",
    "desteldonk": "East Flanders",
    "sint-truiden": "Limburg",
    "regio antwerpen": "Antwerp",
    "sint-katelijne-waver": "Antwerp",
    "tongeren": "Limburg",
    "bornem": "Antwerp",
    "provincie oost-vlaanderen": "East Flanders",
    "gavere": "East Flanders",
    "avelgem": "West Flanders",
    "knokke-heist": "West Flanders",
    "zwijndrecht": "Antwerp",
    "hooglede": "West Flanders",
    "sint-eloois-vijve": "West Flanders",
    "halle": "Flemish Brabant",
    "paal": "Limburg",
    "mol": "Antwerp",
    "wilrijk": "Antwerp",
    "zwevezele": "West Flanders",
    "sint-joost-ten-node": "Brussels-Capital Region",
    "groot-bijgaarden": "Flemish Brabant",
    "aarschot": "Flemish Brabant",
    "ingelmunster": "West Flanders",
    "buggenhout": "East Flanders",
    "lochristi": "East Flanders",
    "sint-gillis": "Brussels-Capital Region",
    "asse": "Flemish Brabant",
    "lummen": "Limburg",
    "moeskroen": "Hainaut",
    "melle": "East Flanders",
    "gullegem": "West Flanders",
    "beerse": "Antwerp",
    "bree": "Limburg",
    "kallo": "East Flanders",
    "ruiselede": "West Flanders",
    "staden": "West Flanders",
    "zonhoven": "Limburg",
    "gits": "West Flanders",
    "bissegem": "West Flanders",
    "beringen": "Limburg",
    "oostkamp": "West Flanders",
    "regio dendermonde - wetteren": "East Flanders",
    "wommelgem": "Antwerp",
    "hoogstraten": "Antwerp",
    "westerlo": "Antwerp",
    "geraardsbergen": "East Flanders",
    "kluisbergen": "East Flanders",
    "aartselaar": "Antwerp",
    "dilsen-stokkem": "Limburg",
    "diest": "Flemish Brabant",
    "herent": "Flemish Brabant",
    "provincie vlaams-brabant": "Flemish Brabant",
    "machelen": "Flemish Brabant",
    "diepenbeek": "Limburg",
    "diksmuide": "West Flanders",
    "borgerhout": "Antwerp",
    "beveren-leie": "West Flanders",
    "bavikhove": "West Flanders",
    "merksem": "Antwerp",
    "schoten": "Antwerp",
    "ranst": "Antwerp",
    "provincie west-vlaanderen": "West Flanders",
    "oostnieuwkerke": "West Flanders",
    "hamme": "East Flanders",
    "wondelgem": "East Flanders",
    "wervik": "West Flanders",
    "zeebrugge": "West Flanders",
    "destelbergen": "East Flanders",
    "kapellen": "Antwerp",
    "overijse": "Flemish Brabant",
    "beernem": "West Flanders",
    "kruibeke": "East Flanders",
    "regio waasland": "East Flanders",
    "blaasveld": "Antwerp",
    "kampenhout": "Flemish Brabant",
    "rijkevorsel": "Antwerp",
    "halen": "Limburg",
    "eke": "East Flanders",
    "zellik": "Flemish Brabant",
    "herzele": "East Flanders",
    "diegem": "Flemish Brabant",
    "zedelgem": "West Flanders",
    "meer": "Antwerp",
    "maasmechelen": "Limburg",
    "relegem": "Flemish Brabant",
    "sint-gillis-waas": "East Flanders",
    "ledegem": "West Flanders",
    "desselgem": "West Flanders",
    "boortmeerbeek": "Flemish Brabant",
    "regio gent": "East Flanders",
    "sint-andries": "West Flanders",
    "erpe-mere": "East Flanders",
    "kortemark": "West Flanders",
    "gentbrugge": "East Flanders",
    "verrebroek": "East Flanders",
    "torhout": "West Flanders",
    "elsene": "Brussels-Capital Region",
    "ham": "Limburg",
    "veurne": "West Flanders",
    "wemmel": "Flemish Brabant",
    "zwijnaarde": "East Flanders",
    "moorslede": "West Flanders",
    "wilsele": "Flemish Brabant",
    "anderlecht": "Brussels-Capital Region",
    "zutendaal": "Limburg",
    "oostakker": "East Flanders",
    "nieuwpoort": "West Flanders",
    "rotselaar": "Flemish Brabant",
    "oudenburg": "West Flanders",
    "brasschaat": "Antwerp",
    "grimbergen": "Flemish Brabant",
    "adegem": "East Flanders",
    "brakel": "East Flanders",
    "dessel": "Antwerp",
    "landen": "Flemish Brabant",
    "peruwelz": "Hainaut",
    "regio bornem - puurs - willebroek": "Antwerp",
    "koolskamp": "West Flanders",
    "balen": "Antwerp",
    "malle": "Antwerp",
    "hulste": "West Flanders",
    "dudzele": "West Flanders",
    "houthalen": "Limburg",
    "oostvleteren": "West Flanders",
    "wavre": "Walloon Brabant",
    "lievegem": "East Flanders",
    "etterbeek": "Brussels-Capital Region",
    "strombeek-bever": "Flemish Brabant",
    "bilzen": "Limburg",
    "meerhout": "Antwerp",
    "houthalen-helchteren": "Limburg",
    "moen": "West Flanders",
    "wolvertem": "Flemish Brabant",
    "zwalm": "East Flanders",
    "melsele": "East Flanders",
    "herk-de-stad": "Limburg",
    "lendelede": "West Flanders",
    "horebeke": "East Flanders",
    "blankenberge": "West Flanders",
    "de haan": "West Flanders",
    "heule": "West Flanders",
    "regio mechelen": "Antwerp",
    "evere": "Brussels-Capital Region",
    "duffel": "Antwerp",
    "nijlen": "Antwerp",
    "mortsel": "Antwerp",
    "sint-denijs-westrem": "East Flanders",
    "laarne": "East Flanders",
    "sint-stevens-woluwe": "Flemish Brabant",
    "lauwe": "West Flanders",
    "bavegem": "East Flanders",
    "lubbeek": "Flemish Brabant",
    "koksijde": "West Flanders",
    "lebbeke": "East Flanders",
    "hamont-achel": "Limburg",
    "neder-over-heembeek": "Brussels-Capital Region",
    "jette": "Brussels-Capital Region",
    "ekeren": "Antwerp",
    "brecht": "Antwerp",
    "provincie limburg": "Limburg",
    "edegem": "Antwerp",
    "maaseik": "Limburg",
    "zelzate": "East Flanders",
    "niel": "Antwerp",
    "zonnebeke": "West Flanders",
    "komen": "West Flanders",
    "rumbeke": "West Flanders",
    "regio boom-aartselaar": "Antwerp",
    "westrozebeke": "West Flanders",
    "tielt-winge": "Flemish Brabant",
    "rumst": "Antwerp",
    "herenthout": "Antwerp",
    "oudergem": "Brussels-Capital Region",
    "boom": "Antwerp",
    "sint-lievens-houtem": "East Flanders",
    "zemst": "Flemish Brabant",
    "nivelles": "Walloon Brabant",
    "oud-turnhout": "Antwerp",
    "bekkevoort": "Flemish Brabant",
    "lichtervelde": "West Flanders",
    "vichte": "West Flanders",
    "kortenberg": "Flemish Brabant",
    "kasterlee": "Antwerp",
    "putte": "Antwerp",
    "kalken": "East Flanders",
    "bocholt": "Limburg",
    "lanaken": "Limburg",
    "dilbeek": "Flemish Brabant",
    "stekene": "East Flanders",
    "essen": "Antwerp",
    "meetkerke": "West Flanders",
    "emelgem": "West Flanders",
    "dadizele": "West Flanders",
    "gistel": "West Flanders",
    "blandain": "Hainaut",
    "hoeselt": "Limburg",
    "laakdal": "Antwerp",
    "riemst": "Limburg",
    "jabbeke": "West Flanders",
    "regio halle": "Flemish Brabant",
    "pittem": "West Flanders",
    "schaarbeek": "Brussels-Capital Region",
    "lede": "East Flanders",
    "aarsele": "West Flanders",
    "afsnee": "East Flanders",
    "kachtem": "West Flanders",
    "alken": "Limburg",
    "de panne": "West Flanders",
    "haren (brussel-stad)": "Brussels-Capital Region",
    "kessel-lo": "Flemish Brabant",
    "regio beringen - tessenderlo": "Limburg",
    "brucargo": "Flemish Brabant",
    "ganshoren": "Brussels-Capital Region",
    "lanklaar": "Limburg",
    "lissewege": "West Flanders",
    "pulle": "Antwerp",
    "bredene": "West Flanders",
    "mariakerke": "East Flanders",
    "bonheiden": "Antwerp",
    "meise": "Flemish Brabant",
    "nieuwerkerken": "East Flanders",
    "oosterzele": "East Flanders",
    "peer": "Limburg",
    "herne": "Flemish Brabant",
    "braine-l'alleud": "Walloon Brabant",
    "zandhoven": "Antwerp",
    "houthulst": "West Flanders",
    "regio turnhout": "Antwerp",
    "keerbergen": "Flemish Brabant",
    "vorst": "Brussels-Capital Region",
    "steenokkerzeel": "Flemish Brabant",
    "regio asse": "Flemish Brabant",
    "merksplas": "Antwerp",
    "sint-jans-molenbeek": "Brussels-Capital Region",
    "affligem": "Flemish Brabant",
    "sint-michiels": "West Flanders",
    "vilvoorde cargovil": "Flemish Brabant",
    "kalmthout": "Antwerp",
    "kuringen": "Limburg",
    "dentergem": "West Flanders",
    "tournai": "Hainaut",
    "borgloon": "Limburg",
    "bellegem": "West Flanders",
    "regio leuven": "Flemish Brabant",
    "rekkem": "West Flanders",
    "oudegem": "East Flanders",
    "haacht": "Flemish Brabant",
    "ruddervoorde": "West Flanders",
    "merchtem": "Flemish Brabant",
    "drogenbos": "Flemish Brabant",
    "regio herentals - westerlo": "Antwerp",
    "regio ninove - geraardsbergen - zottegem": "East Flanders",
    "loppem": "West Flanders",
    "assenede": "East Flanders",
    "court-saint-etienne": "Walloon Brabant",
    "borsbeke": "East Flanders",
    "sint-pieters-leeuw": "Flemish Brabant",
    "sint-martens-latem": "East Flanders",
    "gijzegem": "East Flanders",
    "stabroek": "Antwerp",
    "leopoldsburg": "Limburg",
    "muizen": "Antwerp",
    "berlare": "East Flanders",
    "roosdaal": "Flemish Brabant",
    "vlaanderen": "Flanders",
    "luik": "Liège",
    "regio hasselt": "Limburg",
    "louvain-la-neuve": "Walloon Brabant",
    "regio kontich - mortsel - ranst": "Antwerp",
    "ichtegem": "West Flanders",
    "welle": "East Flanders",
    "langemark": "West Flanders",
    "mollem": "Flemish Brabant",
    "beselare": "West Flanders",
    "berlaar": "Antwerp",
    "boutersem": "Flemish Brabant",
    "wuustwezel": "Antwerp",
    "hemiksem": "Antwerp",
    "huizingen": "Flemish Brabant",
    "lessines": "Hainaut",
    "regio genk": "Limburg",
    "hoboken": "Antwerp",
    "kinrooi": "Limburg",
    "assebroek": "West Flanders",
    "dworp": "Flemish Brabant",
    "tisselt": "Antwerp",
    "hannuit": "Liège",
    "beveren-aan-den-ijzer": "West Flanders",
    "langemark-poelkapelle": "West Flanders",
    "hoegaarden": "Flemish Brabant",
    "begijnendijk": "Flemish Brabant",
    "wiekevorst": "Antwerp",
    "hillegem": "East Flanders",
    "chaudfontaine": "Liège",
    "leest": "Antwerp",
    "lot": "Flemish Brabant",
    "ukkel": "Brussels-Capital Region",
    "regio roeselare - izegem": "West Flanders",
    "grace-hollogne": "Liège",
    "watermaal-bosvoorde": "Brussels-Capital Region",
    "sint-agatha-berchem": "Brussels-Capital Region",
    "regio aalst": "East Flanders",
    "ruisbroek": "Flemish Brabant",
    "haaltert": "East Flanders",
    "dottenijs": "Hainaut",
    "vorselaar": "Antwerp",
    "gierle": "Antwerp",
    "steenhuffel": "Flemish Brabant",
    "vlezenbeek": "Flemish Brabant",
    "zuienkerke": "West Flanders",
    "koekelberg": "Brussels-Capital Region",
    "moorsel": "Flemish Brabant",
    "middelkerke": "West Flanders",
    "komen-waasten": "West Flanders",
    "beveren (roeselare)": "West Flanders",
    "lembeke": "East Flanders",
    "oedelem": "West Flanders",
    "kessel": "Antwerp",
    "huldenberg": "Flemish Brabant",
    "regio kortrijk": "West Flanders",
    "schilde": "Antwerp",
    "aalbeke": "West Flanders",
    "otegem": "West Flanders",
    "mater": "East Flanders",
    "egem": "West Flanders",
    "geluwe": "West Flanders",
    "damme": "West Flanders",
    "bottelare": "East Flanders",
    "lint": "Antwerp",
    "proven": "West Flanders",
    "westkerke": "West Flanders",
    "regio vilvoorde - zaventem": "Flemish Brabant",
    "maarkedal": "East Flanders",
    "wellen": "Limburg",
    "ertvelde": "East Flanders",
    "regio brugge": "West Flanders",
    "borsbeek": "Antwerp",
    "aartrijke": "West Flanders",
    "denderhoutem": "East Flanders",
    "asper": "East Flanders",
    "brielen": "West Flanders",
    "handzame": "West Flanders",
    "marke": "West Flanders",
    "bouwel": "Antwerp",
    "ophasselt": "East Flanders",
    "kaulille": "Limburg",
    "waasmunster": "East Flanders",
    "sint-kruis": "West Flanders",
    "beersel": "Flemish Brabant",
    "thines": "Walloon Brabant",
    "hever": "Flemish Brabant",
    "regio diksmuide": "West Flanders",
    "perwez": "Walloon Brabant",
    "heuvelland": "West Flanders",
    "nederzwalm-hermelgem": "East Flanders",
    "bazel": "East Flanders",
    "weelde": "Antwerp",
    "gooik": "Flemish Brabant",
    "regio tongeren - maasmechelen": "Limburg",
    "lo-reninge": "West Flanders",
    "sint-lambrechts-woluwe": "Brussels-Capital Region",
    "hechtel-eksel": "Limburg",
    "bovekerke": "West Flanders",
    "westmalle": "Antwerp",
    "borchtlombeek": "Flemish Brabant",
    "sint-lenaarts": "Antwerp",
    "sint-laureins": "East Flanders",
    "waterloo": "Walloon Brabant",
    "peutie": "Flemish Brabant",
    "schelle": "Antwerp",
    "moerzeke": "East Flanders",
    "mouscron": "Hainaut",
    "bevere": "East Flanders",
    "silly": "Hainaut",
    "dottignies": "Hainaut",
    "poppel": "Antwerp",
    "krombeke": "West Flanders",
    "baulers": "Walloon Brabant",
    "sleidinge": "East Flanders",
    "gontrode": "East Flanders",
    "massemen": "East Flanders",
    "regio oudenaarde - ronse - brakel": "East Flanders",
    "velm": "Limburg",
    "humbeek": "Flemish Brabant",
    "ressegem": "East Flanders",
    "regio luik": "Liège",
    "belsele": "East Flanders",
    "wichelen": "East Flanders",
    "oekene": "West Flanders",
    "tervuren": "Flemish Brabant",
    "eernegem": "West Flanders",
    "holsbeek": "Flemish Brabant",
    "kaprijke": "East Flanders",
    "vrasene": "East Flanders",
    "baasrode": "East Flanders",
    "westende": "West Flanders",
    "ravels": "Antwerp",
    "belgië": "Belgium",
    "rekem": "Limburg",
    "heusden": "Limburg",
    "kermt": "Limburg",
    "regio oostende": "West Flanders",
    "regio overpelt - hamont-achel - lommel": "Limburg",
    "koekelare": "West Flanders",
    "sint-genesius-rode": "Flemish Brabant",
    "zoersel": "Antwerp",
    "molenstede": "Flemish Brabant",
    "nossegem": "Flemish Brabant",
    "beerzel": "Antwerp",
    "fleurus": "Hainaut",
    "liedekerke": "Flemish Brabant",
    "geetbets": "Flemish Brabant",
    "denderleeuw": "East Flanders",
    "mont-saint-guibert": "Walloon Brabant",
    "ghislenghien": "Hainaut",
    "regio kalmthout - schoten - zoersel": "Antwerp",
    "eindhout": "Antwerp",
    "nieuwrode": "Flemish Brabant",
    "lille": "Antwerp",
    "spiere-helkijn": "West Flanders",
    "passendale": "West Flanders",
    "laken (brussel-stad)": "Brussels-Capital Region",
    "wachtebeke": "East Flanders",
    "sint-amandsberg": "East Flanders",
    "glabbeek-zuurbemde": "Flemish Brabant",
    "heers": "Limburg",
    "lombardsijde": "West Flanders",
    "vise": "Liège",
    "koningshooikt": "Antwerp",
    "northcote; vic": "Antwerp",
    "boechout": "Antwerp",
    "sivry": "Hainaut",
    "gingelom": "Limburg",
    "regio londerzeel": "Flemish Brabant",
    "vladslo": "West Flanders",
    "oevel": "Antwerp",
    "bouffioulx": "Hainaut",
    "arquennes": "Hainaut",
    "regio doel": "East Flanders",
    "binkom": "Flemish Brabant",
    "froyennes": "Hainaut",
    "sint-jan-in-eremo": "East Flanders",
    "pamel": "Flemish Brabant",
    "bierges": "Walloon Brabant",
    "tourpes": "Hainaut",
    "denderwindeke": "East Flanders",
    "walem": "Antwerp",
    "ramegnies-chin": "Hainaut",
    "alveringem": "West Flanders",
    "seraing": "Liège",
    "neeroeteren": "Limburg",
    "kieldrecht": "East Flanders",
    "leupegem": "East Flanders",
    "elewijt": "Flemish Brabant",
    "martenslinde": "Limburg",
    "soignies": "Hainaut",
    "vlimmeren": "Antwerp",
    "kortenaken": "Flemish Brabant",
    "beauvechain": "Walloon Brabant",
    "sittard": "Limburg",
    "dison": "Liège",
    "couillet": "Hainaut",
    "lichtaart": "Antwerp",
    "boezinge": "West Flanders",
    "boekhoute": "East Flanders",
    "schulen": "Limburg",
    "sint-job-in-'t-goor": "Antwerp",
    "veerle": "Limburg",
    "kapelle-op-den-bos": "Flemish Brabant",
    "zandvoorde": "West Flanders",
    "vivegnis": "Liège",
    "barchon": "Liège",
    "assent": "Flemish Brabant",
    "regio sint-truiden": "Limburg",
    "henri-chapelle": "Liège",
    "vlamertinge": "West Flanders",
    "regio lier - heist o/d berg": "Antwerp",
    "regio waregem": "West Flanders",
    "vleteren": "West Flanders",
    "hoeilaart": "Flemish Brabant",
    "wimmertingen": "Limburg",
    "arlon": "Luxembourg",
    "itterbeek": "Flemish Brabant",
    "koersel": "Limburg",
    "sint-martens-lennik": "Flemish Brabant",
    "regio antwerpen (b) - noord-brabant (nl)": "Antwerp",
    "wijgmaal": "Flemish Brabant",
    "munsterbilzen": "Limburg",
    "regio limburg (b) - limburg (nl)": "Limburg",
    "wieze": "East Flanders",
    "leffinge": "West Flanders",
    "oelegem": "Antwerp",
    "heikruis": "Flemish Brabant",
    "cambron-casteau": "Hainaut",
    "beveren-roeselare": "West Flanders",
    "s herenelderen": "Limburg",
    "sint-maria-lierde": "East Flanders",
    "edingen": "Hainaut",
    "herstal": "Liège",
    "kortessem": "Limburg",
    "amougies": "Hainaut",
    "opwijk": "Flemish Brabant",
    "loncin": "Liège",
    "mont-de-l'enclus": "Hainaut",
    "bevel": "Antwerp",
    "leuze-en-hainaut": "Hainaut",
    "schuiferskapelle": "West Flanders",
    "comines": "Hainaut",
    "elversele": "East Flanders",
    "averbode": "Flemish Brabant",
    "messelbroek": "Flemish Brabant",
    "outer": "East Flanders",
    "jumet": "Hainaut",
    "sambreville": "Namur",
    "kraainem": "Flemish Brabant",
    "tielen": "Antwerp",
    "herdersem": "East Flanders",
    "bambrugge": "East Flanders",
    "boorsem": "Limburg",
    "oplinter": "Flemish Brabant",
    "lennik": "Flemish Brabant",
    "weerde": "Flemish Brabant",
    "nieuwkerke": "West Flanders",
    "sint-joris-weert": "Flemish Brabant",
    "scherpenheuvel": "Flemish Brabant",
    "hamont": "Limburg",
    "scheldewindeke": "East Flanders",
    "munkzwalm": "East Flanders",
    "sint-gillis-bij-dendermonde": "East Flanders",
    "hechtel": "Limburg",
    "schriek": "Antwerp",
    "reet": "Antwerp",
    "estaimpuis": "Hainaut",
    "sint-joris-winge": "Flemish Brabant",
    "rupelmonde": "East Flanders",
    "waterland-oudeman": "East Flanders",
    "herselt": "Antwerp",
    "gembloux": "Namur",
    "scherpenheuvel-zichem": "Flemish Brabant",
    "burcht": "East Flanders",
    "weert": "Limburg",
    "stevoort": "Limburg",
    "champion": "Namur",
    "regio tielt": "West Flanders",
    "sint-pieters-woluwe": "Brussels-Capital Region",
    "marquain": "Hainaut",
    "oostmalle": "Antwerp",
    "betekom": "Flemish Brabant",
    "fontenoy": "Hainaut",
    "celles": "Hainaut",
    "hoepertingen": "Limburg",
    "regio eeklo - zelzate": "East Flanders",
    "broechem": "Antwerp",
    "herfelingen": "Flemish Brabant",
    "provincie namen": "Namur",
    "dilsen": "Limburg",
    "sint-martens-bodegem": "Flemish Brabant",
    "manage": "Hainaut",
    "berlingen": "Limburg",
    "kerkhove": "West Flanders",
    "tubize": "Walloon Brabant",
    "wiesme": "Hainaut",
    "moerbeke-waas": "East Flanders",
    "zoutleeuw": "Flemish Brabant",
    "eppegem": "Flemish Brabant",
    "jemeppe-sur-sambre": "Namur",
    "sint-katherina-lombeek": "Flemish Brabant",
    "schepdaal": "Flemish Brabant",
    "rixensart": "Walloon Brabant",
    "moorsele": "West Flanders",
    "daknam": "East Flanders",
    "olsene": "East Flanders",
    "hertsberge": "West Flanders",
    "bierbeek": "Flemish Brabant",
    "retie": "Antwerp",
    "rillaar": "Flemish Brabant"
}

In [7]:
# Function to map location to province
def map_location_to_province(location):
    return location_province_mapping.get(location.lower(), "Unknown")

# Apply the mapping function to create a new column
vdab_jobs['province'] = vdab_jobs['location'].apply(map_location_to_province)

In [8]:
vdab_jobs

,Unnamed: 0.1,Unnamed: 0,url,title,employer,location,description,description_translated,title_translated,keywords,top_categories,province
0,0,0,https://www.vdab.be/vindeenjob/vacatures/68793122,technisch aankoopassistent,le grand & associates,kortrijk,Functieomschrijving LGA Engineering is een rek...,Job description LGA Engineering is a recruitme...,technical purchasing assistant,"{'Profile Profile Experience', 'recruitment', ...","['Administration', 'Sales', 'Logistics, transp...",West Flanders
1,1,1,https://www.vdab.be/vindeenjob/vacatures/68793123,pricing analist,lga engineering,provincie vlaams-brabant,Functieomschrijving Heb jij een passie voor de...,Job description Do you have a passion for the ...,pricing analist,"{'Job', 'career', 'job', 'competencies', 'logi...","['Sales', 'Administration', 'Creative jobs']",Flemish Brabant
2,2,2,https://www.vdab.be/vindeenjob/vacatures/68793124,pricing analist maritiem,lga engineering,antwerpen,Functieomschrijving Voor onze logistieke klant...,Job description For our logistics customer in ...,maritime pricing analyst,"{'Job', 'Offer Offer', 'contract prices', 'Ana...","['Administration', 'Sales', 'Logistics, transp...",Antwerp
3,3,3,https://www.vdab.be/vindeenjob/vacatures/68793125,warehouse teamleader,start people,herentals,Functieomschrijving Onze klant gevestigd in He...,Job description Our client based in Herentals ...,warehouse team leader,"{'operating logistics', 'role', 'globally oper...","['Administration', 'Logistics, transport & pur...",Antwerp
4,4,4,https://www.vdab.be/vindeenjob/vacatures/68793126,grafisch vormgever,start people,pelt,Functieomschrijving 1 op de 10 gezinnen geniet...,Job description 1 in 10 families already enjoy...,graphical designer,"{'Job', 'designing', 'wooden windows', 'doors'...","['Administration', 'Sales', 'Creative jobs']",Limburg
...,...,...,...,...,...,...,...,...,...,...,...,...
11122,11122,11122,https://www.vdab.be/vindeenjob/vacatures/68804504,plaatser - glazen binnenwanden,forum construct maldegem,oostkamp,Functieomschrijving Voor onze klant zijn wij o...,Job description We are looking for an installe...,installer - glass interior walls,"{'glass', 'West Flanders region', 'GLASS INTER...","['Administration', 'Logistics, transport & pur...",West Flanders
11123,11123,11123,https://www.vdab.be/vindeenjob/vacatures/68804505,heftruckchauffeur,forum jobs-food-construct roeselare,roeselare,Functieomschrijving Als heftruckchauffeur sta ...,Job description As a forklift driver you are r...,forklift driver,"{'equipment', '3rd grade', 'deviations Report ...","['Administration', 'Logistics, transport & pur...",West Flanders
11124,11124,11124,https://www.vdab.be/vindeenjob/vacatures/68804506,technisch coördinator (+ bedrijfswagen),square city,evergem,Functieomschrijving Verwacht het onverwachte v...,Job description Expect the unexpected for your...,technical coordinator (+ company car),"{'Technical', 'maintenance', 'supervise', 'res...","['Administration', 'Sales', 'Logistics, transp...",East Flanders
11125,11125,11125,https://www.vdab.be/vindeenjob/vacatures/68804507,mechanieker,forum jobs-food-construct roeselare,roeselare,Functieomschrijving Als mechanieker behoort to...,"Job description As a mechanic, your duties inc...",mechanic,"{'equipment', 'mechanical pieces', 'maintenanc...","['Logistics, transport & purchase', 'Administr...",West Flanders
11126,11126,11126,https://www.vdab.be/vindeenjob/vacatures/68804508,kraanmachinist,vivaldis construct,harelbeke,Functieomschrijving Voor onze klant te Harelbe...,Job description For our customer in Harelbeke;...,crane operator,"{'TYRE CRANE OPERATOR', 'TYPE CRANE', 'TYRE', ...","['Administration', 'Sales', 'Creative jobs']",West Flanders

In [17]:
vdab_jobs.to_csv('C:/Users/Cool_/Documents/GitHub/PPA/hr_tool_irakli/VDAB_categories_provinces.csv', index=False)